language: python
sudo: false
python:
- 2.7
- 3.3
before_install:
- pip install -r requirements.txt
- pip install pytest mock pretend freezegun
- pip install -e .
- git config --global user.email "gitbot@adamcoddington.net"
- git config --global user.name "I'm a Robot"
script: py.test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a79205de9fd79c70ee19
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
env:
  global:
  - secure: kvHtlbvzL0JOQ9nhO5yqXnIL6uDfxR6FWZIUz169AUuzUp4Vz7W40QESKwZzRsg5W7sIel8Sshy2X+sSXmqVFK9wDliPVYlaP+TXyRSdrRqfspXMJyIeGnfArqfQMmADmq6VdfwoPguwsVvXIH2r6gAiUC4sFONXnzOph4wiRV0=
  - secure: KIalo50Z25X7EIOf4dMK02F58o2RLQsZdMQuZMz+3UYCj1Vjfv0v+a++n9t4Bb2/uFTMCmK7ipNeT0cmY8pOHR2kWY6RbfTZfiMxXyhgPzJrhvzoyy5Jp1MCJ3/ESo4CJzVlGc6BRXP71QkFoZ0+Y3z/CxYRHbwFFBPT6MObSyI=
  - secure: i/AEZ+kS7t4gIdGnF7deMaJlvGWic4lnQhMZHPhAV/nWkH3ZH67QuH25vCEZZXy7yo24dIhzEuekFzHVj0/qqR1UCddzruUVBmINjfodcSGnjAAxwovKC+JBKjnQE0fbTSsXrwOvpivLrGtI9fKBWoH3c0o/jWYEI2JWQeJRlPA=
  - secure: eyLQII1VRTOjPRMmSsHODR/7KVzLZi+agoSJFW8zMJCwecM9784eDXhWxw9qakgLCng15tATr8pVP50wplJq0Wc+qRBxXkIuqunJ9hSeFRGOrgRvsj8UvPiU9sq4x+XUK1KJWNP8a5czsEGilx6JuQ943B45HG2qY5sYhtkKcCc=
